site_name: DeepWork Cookiecutter Project Template
site_description: This cookiecutter template serves to create the boilerplate code for a new DeepWork project.
site_author: Deepworks
copyright: Deepworks 2023
repo_url: https://github.com/deepworks-net/dw-project-template
extra:
    version: 0.2.0
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
    name: material
    icon:
      logo: simple/cookiecutter
    features:
        - navigation.instant
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - content.code.copy
        - content.tabs
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
        - search.share
    palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
'nav':
    - 'Home': 'index.md'
    - 'About':
        - 'Contributing': 'about/contributing.md'
        - 'Code of Conduct': 'about/code-of-conduct.md'
