site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_short_description }}
site_author: {{ cookiecutter.full_name }}
copyright: {{ cookiecutter.full_name }} {% now 'utc', '%Y' %}
repo_url: https://github.com/{{ cookiecutter.project_slug }}
extra:
    version: 0.1.0
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.indexes
        - navigation.top
        - content.code.copy
        - content.tabs
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
        - search.share
    palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
'nav':
    - 'Home': 'index.md'
    - 'About':
        - 'Contributing': 'about/contributing.md'
        - 'Code of Conduct': 'about/code-of-conduct.md'
